name: CPP Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testbranches: ['release','master']

    steps:
      - uses: actions/checkout@v2

      - name: Apt update
        run: sudo apt update
        
      - name: Customize git
        run: |
          git submodule update --init --recursive
        
      - name: Install prerequisites
        run: |
          sudo apt install cmake g++ libeigen3-dev dpkg-dev build-essential
          
      - name: Build & install DQRobotics (${{ matrix.testbranches }})
        run: |
          git clone -b ${{ matrix.testbranches }} https://github.com/dqrobotics/cpp
          cd cpp
          dpkg-buildpackage --sanitize-env -us -uc -B -rfakeroot
          cd ..
          sudo apt install ./*.deb
          
      - name: Build & install cpp-interface-json11
        run: |
          dpkg-buildpackage --sanitize-env -us -uc -B -rfakeroot
          cd ..
          sudo apt install ./*.deb
          
      - name: Clone cpp-examples (${{ matrix.testbranches }})
        run: git clone -b ${{ matrix.testbranches }} https://github.com/dqrobotics/cpp-examples.git
          
      - name: Build and run example
        run: |
          cd cpp-examples
          chmod +x .build_json11.sh
          ./.build_json11.sh
